console.log(document.getElementById("main-heading"))
console.dir(document.getElementById("main-heading"))
console.log(typeof document.getElementById("main-heading"))
console.log(document.getElementsByClassName("headline"))
console.dir(document.getElementsByClassName("headline"))
console.log(document.getElementById("test"))
console.dir(document.getElementsByClassName("logo"))

const logo = document.getElementsByClassName("logo")
console.log("logo = ", logo)
console.dir("logo = ", logo)
